version: '2.1'
orbs:
  qodana: jetbrains/qodana@2023.2
jobs:
  code-quality:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - checkout
      # install dependencies
      - run:
          name: install dependencies
          command: npm install
      - qodana/scan
workflows:
  main:
    jobs:
      - code-quality:
          context: qodana
